### ISSUE TITLE
Configurable list of fingerprint selectors for push request reactions

### ISSUE THREAD

**Issue by ludovicc** [atomist/sdm-pack-fingerprints#18]
The list of selectors is hard-coded, could it become configurable, to select new selectors for other types of libraries (Docker images, Python/Scala libraries...)
https://github.com/atomist/sdm-pack-fingerprints/blob/master/lib/handlers/events/pushImpactHandler.ts#L165

**Comment by slimslenderslacks** [comment]
@ludovicc took a long time to get back to this, but this was moved out into the fingerprintSupport function so you can define these handlers outside of the pack.  There's an example here:

https://github.com/atomist/sdm-pack-fingerprints

We're going to add the following examples over the next week:

- fingerprinting an appender from a logback configuration file
- fingerprinting your docker base image 
- fingerprinting a snippet from a node package.json file 
- fingerprinting a shareable plugin config from a maven pom.xml file
- fingerprint a tslint config file

**Comment by ludovicc** [comment]
Thanks @slimslenderslacks
