### ISSUE TITLE
Improve build

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-pack-fingerprints#70]
`npm run clean` followed by `npm run build` fails unless using `atomist gql-fetch`.

Can this be automated as part of the build? It would be confusing for end users.

**Comment by slimslenderslacks** [comment]
Yes, looks like a good npm run:clean script is now:

```
    "clean:compile": "rimraf git-info.json build \"index.{d.ts,js{,.map}}\" \"{lib,test}/**/*.{d.ts,js{,.map}}\" lib/typings/types.ts",

```

This preserves the schema.json output from atomist gql-fetch
